import { FaExclamationCircle } from "react-icons/fa";
import { FaRegCircle, FaRegCircleCheck } from "react-icons/fa6";
// import { GrDocument } from "react-icons/gr";
import {
  IoIosCheckmarkCircleOutline,
  IoIosCloseCircleOutline,
} from "react-icons/io";
import { TiDocumentAdd } from "react-icons/ti";
export const navbarData = [
  {
    path: "/production-planning",
    text: "production planning dashboard",
  },
  // {
  //   path: "/scm",
  //   text: "SCM dashbaord",
  // },
  // {
  //   path: "/inventory",
  //   text: "inventory dashboard",
  // },
  // {
  //   path: "/manpower-planning",
  //   text: "manpower planning dashboard",
  // },
  {
    path: "/masters",
    text: "masters",
  },
  {
    path: "/weekly-entry",
    text: "Weekly Entry",
  },
  {
    path: "/production-calendar",
    text: "Production Calendar",
  },
];
export const productionPlanningSelections = {
  factory: ["Factory A", "Factory B", "Factory C"],
  department: ["HR", "Business Analyst", "Marketing", "Engineers"],
  machine: ["Machine 1", "Machine 2", "Machine 3", "Machine 4"],
};
export const productionPlanningCardsData = [
  {
    bgColor: "bg-blue-100",
    borderColor: "border-blue-200",
    icon: TiDocumentAdd,
    iconColor: "text-blue-700",
    iconBgColor: "bg-blue-300",
    title: "Plan",
    measure: "123",
    unit: "Units",
  },
  {
    bgColor: "bg-green-100",
    borderColor: "border-green-200",
    icon: FaRegCircleCheck,
    iconColor: "text-green-700",
    iconBgColor: "bg-green-300",
    title: "Produced",
    measure: "4,720",
    unit: "Units",
  },
  {
    bgColor: "bg-gray-100",
    borderColor: "border-gray-200",
    icon: FaRegCircleCheck,
    iconColor: "text-gray-700",
    iconBgColor: "bg-gray-300",
    title: "Avg cycle time",
    measure: "255.84",
    unit: "sec",
  },
  {
    bgColor: "bg-red-100",
    borderColor: "border-red-200",
    icon: FaRegCircleCheck,
    iconColor: "text-red-700",
    iconBgColor: "bg-red-300",
    title: "Rejection",
    measure: "255.84",
    unit: "sec",
  },
  {
    bgColor: "bg-yellow-100",
    borderColor: "border-yellow-200",
    icon: IoIosCloseCircleOutline,
    iconColor: "text-yellow-700",
    iconBgColor: "bg-yellow-300",
    title: "Utilization",
    measure: "255.84",
    unit: "sec",
  },
];
export const tableData = [
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
  {
    id: 1,
    jobNo: "#34234",
    machine: "Robot Arm",
    productName: "Car",
    planUnits: 12000,
    producedUnits: 2000,
    status: "Pending",
  },
];
export const scmDashboardCardsInfo = [
  {
    title: "order fulfilment",
    icon: IoIosCheckmarkCircleOutline,
    measurement: 93.3,
    measurementText: "",
    unit: "%",
    orderDelivered: 3200,
    chartValue: 93.3,
    color: "text-green-600",
    bgColor: "bg-green-200",
    chartColor: "#04A841",
  },
  {
    title: "procurement progress",
    icon: FaRegCircle,
    measurement: 78,
    measurementText: "",
    unit: "%",
    orderReceived: 2910,
    chartValue: 78,
    color: "text-yellow-600",
    bgColor: "bg-yellow-200",
    chartColor: "#FFDF20",
  },
  {
    title: "total shortages",
    icon: FaExclamationCircle,
    measurement: 86,
    measurementText: "Critical Shortages",
    unit: "",
    todayShortages: 6,
    chartValue: 0,
    color: "text-red-600",
    bgColor: "bg-red-200",
    chartColor: "#FFDF20",
  },
  {
    title: "pending prs",
    icon: FaExclamationCircle,
    measurement: 153,
    measurementText: "PR Requests",
    unit: "",
    todayShortages: 6,
    color: "text-blue-600",
    bgColor: "bg-blue-200",
    chartColor: "#FFDF20",
    moreInfo: [
      {
        name: "Delayed",
        barValue: 40,
        totalbarValue: 100,
        bgColor: "bg-red-300",
        color: "bg-red-700",
      },
      {
        name: "ON-GOING",
        barValue: 76,
        totalbarValue: 100,
        color: "bg-yellow-700",
        bgColor: "bg-yellow-300",
      },
      {
        name: "Arriving-Soon",
        barValue: 40,
        totalbarValue: 100,
        color: "bg-gray-700",
        bgColor: "bg-gray-300",
      },
    ],
  },
];
export const masters = [
  {
    title: "Plant",
    description: "This is the Master for the Plant.",
    masterTable: [
      {
        plantId: "1",
        plantName: "IFB gujarat",
      },
      {
        plantId: "2",
        plantName: "IFB palwal",
      },
      {
        plantId: "3",
        plantName: "IFB Haryana",
      },
    ],
  },
  {
    title: "Assembly Line",
    description: "This is the Master for the Plant assembly line",
    masterTable: [
      {
        assemblyLineId: "1",
        assemblyLineName: "Line 1",
      },
      {
        assemblyLineId: "2",
        assemblyLineName: "Line 2",
      },
      {
        assemblyLineId: "3",
        assemblyLineName: "Line 3",
      },
    ],
  },
  {
    title: "Parts",
    description: "This is the Master for the finished Goods",
    masterTable: [
      {
        partNumber: "1",
        partName: "Compressor",
        childPartList: [
          {
            partCode: "1",
            description: "Nut bolt",
            qty: 2,
          },
          {
            partCode: "2",
            description: "Pipes",
            qty: 3,
          },
          {
            partCode: "3",
            description: "Bearings",
            qty: 2,
          },
        ],
      },
      {
        partNumber: "2",
        partName: "Microwave",
        childPartList: [
          {
            partCode: "4",
            description: "Wire",
            qty: 3,
          },
          {
            partCode: "5",
            description: "PCB",
            qty: 1,
          },
          {
            partCode: "6",
            description: "0",
            qty: 2,
          },
        ],
      },
    ],
  },
  {
    title: "Model",
    description: "This is the Master for the Models.",
    masterTable: [
      {
        mdelId: "1",
        modelName: "Model 1",
      },
      {
        mdelId: "2",
        modelName: "Model 2",
      },
      {
        mdelId: "3",
        modelName: "Model 3",
      },
    ],
  },
  {
    title: "Users",
    description: "This is the Master for the Application users.",
    masterTable: [
      {
        email: "depudagar90@gmail.com",
        password: "deepudagar50",
      },
      {
        email: "admin@gmail.com",
        password: "admin",
      },
      {
        email: "user@gmail.com",
        password: "user",
      },
    ],
  },
];
